language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .[dev]

script:
  - python setup.py run_tests || travis_terminate 1
  - python setup.py build_assets || travis_terminate 1